# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QThread, pyqtSignal
from PyQt5.QtGui import QIcon, QPixmap
from PyQt5.QtWidgets import QMessageBox
import detect
from utils.myutil import file_is_pic, Globals

import pymysql


class Ui_loginWindow(object):


    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(819, 555)
        loginWindow.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        loginWindow.setAttribute(QtCore.Qt.WA_TranslucentBackground)
        self.centralwidget = QtWidgets.QWidget(loginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(73, 41, 340, 490))
        self.label.setStyleSheet("border-image: url(:/images/image/R-C.png);\n"
"border-top-left-radius:30px;\n"
"border-bottom-left-radius:30px;")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(410, 40, 361, 491))
        self.label_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-top-right-radius:30px;\n"
"border-bottom-rightt-radius:30px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.Widget = QtWidgets.QWidget(self.centralwidget)
        self.Widget.setGeometry(QtCore.QRect(500, 120, 174, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.Widget.setFont(font)
        self.Widget.setObjectName("Widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.Widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("#pushButton{\n"
"    border:none;\n"
"}\n"
"#pushButton:focus{\n"
"    color:rgb(186,186,186);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.change_widget2)
        self.horizontalLayout.addWidget(self.pushButton)
        self.line = QtWidgets.QFrame(self.Widget)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout.addWidget(self.line)
        self.pushButton_2 = QtWidgets.QPushButton(self.Widget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("#pushButton_2{\n"
"    border:none;\n"
"}\n"
"#pushButton_2:focus{\n"
"    color:rgb(186,186,186);\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")

        self.pushButton_2.clicked.connect(self.change_widget3)
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.login_1 = QtWidgets.QWidget(self.centralwidget)
        self.login_1.setGeometry(QtCore.QRect(419, 189, 341, 331))
        self.login_1.setObjectName("login_1")
        self.lineEdit_username_1 = QtWidgets.QLineEdit(self.login_1)
        self.lineEdit_username_1.setGeometry(QtCore.QRect(70, 70, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_username_1.setFont(font)
        self.lineEdit_username_1.setStyleSheet("border:lpx solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_username_1.setObjectName("lineEdit_username_1")
        self.lineEdit_password_2 = QtWidgets.QLineEdit(self.login_1)
        self.lineEdit_password_2.setGeometry(QtCore.QRect(70, 160, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_password_2.setFont(font)
        self.lineEdit_password_2.setStyleSheet("border:lpx solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_password_2.setObjectName("lineEdit_password_2")
        self.pushButton_login_2 = QtWidgets.QPushButton(self.login_1)
        self.pushButton_login_2.setGeometry(QtCore.QRect(70, 250, 241, 41))
        self.pushButton_login_2.setStyleSheet("#pushButton_3{\n"
"    background-color:rgb(0,0,0);\n"
"    color:rgb(255,255,255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#pushButton_3:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"}\n"
"#pushButton_3:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_login_2.setObjectName("pushButton_login_2")


        self.checkBox = QtWidgets.QCheckBox(self.login_1)
        self.checkBox.setGeometry(QtCore.QRect(70, 220, 68, 16))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(740, 50, 21, 21))
        self.pushButton_4.setStyleSheet("border:none;")
        self.pushButton_4.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/icon_3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon)
        self.pushButton_4.setObjectName("pushButton_4")
        self.register_1 = QtWidgets.QWidget(self.centralwidget)
        self.register_1.setGeometry(QtCore.QRect(430, 170, 321, 331))
        self.register_1.setObjectName("register_1")
        self.lineEdit_username_3 = QtWidgets.QLineEdit(self.register_1)
        self.lineEdit_username_3.setGeometry(QtCore.QRect(50, 60, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_username_3.setFont(font)
        self.lineEdit_username_3.setStyleSheet("border:lpx solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_username_3.setObjectName("lineEdit_username_3")
        self.lineEdit_password_4 = QtWidgets.QLineEdit(self.register_1)
        self.lineEdit_password_4.setGeometry(QtCore.QRect(50, 120, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_password_4.setFont(font)
        self.lineEdit_password_4.setStyleSheet("border:lpx solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_password_4.setObjectName("lineEdit_password_4")
        self.lineEdit_password_5 = QtWidgets.QLineEdit(self.register_1)
        self.lineEdit_password_5.setGeometry(QtCore.QRect(50, 190, 231, 41))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lineEdit_password_5.setFont(font)
        self.lineEdit_password_5.setStyleSheet("border:lpx solid rgb(0,0,0);\n"
"border-radius:8px;")
        self.lineEdit_password_5.setObjectName("lineEdit_password_5")
        self.pushButton_register_5 = QtWidgets.QPushButton(self.register_1)
        self.pushButton_register_5.setGeometry(QtCore.QRect(50, 260, 241, 41))
        self.pushButton_register_5.setStyleSheet("#pushButton_5{\n"
"    background-color:rgb(0,0,0);\n"
"    color:rgb(255,255,255);\n"
"    border:3px solid rgb(0,0,0);\n"
"    border-radius:8px;\n"
"}\n"
"#pushButton_5:hover{\n"
"    background-color:rgb(255,255,255);\n"
"    color:rgb(0,0,0);\n"
"}\n"
"#pushButton_5:pressed{\n"
"    padding-top:5px;\n"
"    padding-left:5px;\n"
"}")
        self.pushButton_register_5.setObjectName("pushButton_register_5")
        loginWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(loginWindow)
        self.pushButton_4.clicked.connect(loginWindow.close) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(loginWindow)
        self.register_1.hide()

    def change_widget3(self):
        self.register_1.show()
        self.login_1.hide()
    def change_widget2(self):
        self.login_1.show()
        self.register_1.hide()



    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "MainWindow"))
        self.pushButton.setText(_translate("loginWindow", "登录"))
        self.pushButton_2.setText(_translate("loginWindow", "注册"))
        self.lineEdit_username_1.setPlaceholderText(_translate("loginWindow", "账号："))
        self.lineEdit_password_2.setPlaceholderText(_translate("loginWindow", "密码："))
        self.pushButton_login_2.setText(_translate("loginWindow", "登录"))
        self.checkBox.setText(_translate("loginWindow", "记住"))
        self.lineEdit_username_3.setPlaceholderText(_translate("loginWindow", "设置账号："))
        self.lineEdit_password_4.setPlaceholderText(_translate("loginWindow", "输入密码："))
        self.lineEdit_password_5.setPlaceholderText(_translate("loginWindow", "确认密码："))
        self.pushButton_register_5.setText(_translate("loginWindow", "注册"))




import res_rc

